---
title: "Graphical relationship Wallacea birds"
author: "Kushal K Dey"
date: "3/26/2018"
output: html_document
---

Here, we explore a graphical model connecting the different bird species in the entire Wallacea.

```{r message=FALSE, warning=FALSE}
library(igraph)
library(RColorBrewer)
library(ape)
```

```{r}
datalist <- get(load("../data/wallace_region_pres_ab_breeding_no_seabirds.rda"))
latlong <- datalist$loc
data <- datalist$dat
```

```{r}
birds_pa_data_3 <- data
```

```{r}
co_occur_mat <- t(as.matrix(birds_pa_data_3)) %*% as.matrix(birds_pa_data_3)
```

## Minimal Spanning Tree (correlation)

```{r}
cor_dist <- 1 - cov2cor(co_occur_mat)
#system.time(mst2 <- ape::mst(cor_dist));
mst2 <- get(load("../output/mst_wallacea.rda"))
mst2.graph <- igraph::graph.adjacency(as.matrix(mst2));

cols1 <- c(RColorBrewer::brewer.pal(12, "Paired")[c(3,4,7,8,11,12,5,6,9,10)],
           RColorBrewer::brewer.pal(12, "Set3")[c(1,2,5,8,9)],
           RColorBrewer::brewer.pal(9, "Set1")[c(9,7)],
           RColorBrewer::brewer.pal(8, "Dark2")[c(3,4,8)])

plot(mst2.graph,
     edge.arrow.mode=0,
     vertex.size = 5,
     vertex.shape="square",
     vertex.label=NA,
     layout= layout_with_kk
)
```


```{r}
topics_clust <- get(load("../output/methClust_wallacea.rda"))
```

```{r}

cols1 <- c(RColorBrewer::brewer.pal(12, "Paired")[c(3,4,7,8,11,12,5,6,9,10)],
           RColorBrewer::brewer.pal(12, "Set3")[c(1,2,5,8,9)],
           RColorBrewer::brewer.pal(9, "Set1")[c(9,7)],
           RColorBrewer::brewer.pal(8, "Dark2")[c(3,4,8)])

for(k in 2:4){
  freq <- topics_clust[[k]]$freq
  max_clus <- apply(freq, 1, function(x) which.max(x))

plot(mst2.graph,
     edge.arrow.mode=0,
     vertex.size = 5,
     vertex.shape="square",
     vertex.label=NA,
     vertex.color=cols1[as.numeric(max_clus) + 1],
     layout= layout_with_kk
)
 
}


```

